### ISSUE TITLE
Profiler throws exception when the azure monitor connection string is specified through the environment variable and other options are set to enable AuzreMonitor

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azuremonitor-opentelemetry-profiler-net#13]
## Description
The issue happens when:
1. There is a lambda to customize the settings of Azure Monitor, and
2. The connection string is not explicitly set in that lambda.
    * For example, when the connection string is set by environment variable.

## Repro:

Specify connection string by env var:

```ini
APPLICATIONINSIGHTS_CONNECTION_STRING=<Your connection string>
```

Configure the azure monitoring:

```shell
builder.Services.AddOpenTelemetry()
    .UseAzureMonitor(opt =>
    {
        // This bug only impact if this lambda exists.
    })
    .UseProfiler();
```

Run the app.
That works with Azure Monitor Otel, but the value is not recognized by the Profiler, causing exception:

```shell
Unhandled exception. System.InvalidOperationException: A suitable constructor for type 'Microsoft.ApplicationInsights.Profiler.Shared.Services.ConnectionStringParser' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfoEx[] constructors, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)  
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.ApplicationInsights.Profiler.Shared.Services.ConnectionStringParserFactory.Create(String connectionString) in C:\AIR\fork-otel-profiler\src\ServiceProfiler.EventPipe.Otel\Microsoft.ApplicationInsights.Profiler.Shared\Services\ConnectionStringParserFactory.cs:line 13
   at Azure.Monitor.OpenTelemetry.Profiler.Core.ServiceProfilerContext..ctor(IEndpointProvider endpointProvider, IConnectionStringParserFactory connectionStringParserFactory, IOptions`1 options, ILogger`1 logger) in C:\AIR\fork-otel-profiler\src\ServiceProfiler.EventPipe.Otel\Azure.Monitor.OpenTelemetry.Profiler.Core\ServiceProfilerContext.cs:line 32
```

## Expected
As long as the connection string is set in the environment variable, the value should have been passed on to the Profiler for use properly without user interaction.
 
## Workaround:

Either do not specify the options for azure monitor or specify the connection string by code:

```csharp
// Either this
builder.Services.AddOpenTelemetry()
    .UseAzureMonitor()  // There's no action on azure monitor options
    .UseProfiler();

// Or this
builder.Services.AddOpenTelemetry()
    .UseAzureMonitor(opt =>
    {
        // Set the connection string manually or get it from environment variable:
        opt.ConnectionString = "Your-connection-string-here";
    })
    .UseProfiler();
```

**Comment by xiaomi7732** [comment]
Will be fixed in 1.0.0-beta5.
